from django.conf.urls import patterns, include, url

urlpatterns = patterns('getregi.views',
	url(r'^gtdb/$', 'index'),
	url(r'^search/$', 'index_search'),
	url(r'^browse/$', 'index_browse'),
	url(r'^laboratories/$', 'index_laboratory'),
	url(r'^diseases/$', 'index_disease'),
	url(r'^genes/$', 'index_gene'),
#	url(r'^genepanels/$', 'index_genepanel'),
	url(r'^genetictests/$', 'index_genetictest'),
	url(r'^rizivcodes/$', 'index_rizivcode'),
	url(r'^personnel/$', 'index_personnel'),
	url(r'^methodology/$', 'index_methodology'),
	url(r'^laboratories/(?P<laboratory_id>\d+)/$', 'detail_laboratory'),
	url(r'^diseases/(?P<disease_id>\d+)/$', 'detail_disease'),
	url(r'^genes/(?P<gene_id>\d+)/$', 'detail_gene'),
	url(r'^genepanels/(?P<genepanel_id>\d+)/$', 'detail_genepanel'),
	url(r'^genetictests/(?P<genetictest_id>\d+)/$', 'detail_genetictest'),
	url(r'^personnel/(?P<personnel_id>\d+)/$', 'detail_personnel'),
	url(r'^methodcategories/(?P<methodcategory_id>\d+)/$', 'detail_methodcategory'),
	url(r'^methodtechniques/(?P<methodtechnique_id>\d+)/$', 'detail_methodtechnique'),
	url(r'^methodplatforms/(?P<methodplatform_id>\d+)/$', 'detail_methodplatform'),
)
